# Generated by Django 5.1.7 on 2025-03-21 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_app', '0004_remove_car_car_name_remove_car_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='car_image'),
        ),
    ]
