# Generated by Django 5.1.7 on 2025-03-22 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_app', '0009_alter_bid_auction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auction',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
