# Generated by Django 5.1.7 on 2025-03-22 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_app', '0011_alter_car_brand_alter_car_model_favorite_favoritecar'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='task',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
