# Generated by Django 5.1.7 on 2025-03-22 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_app', '0012_car_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='task_en',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='task_ru',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
